services:
  backend:
    build: ./backend
    image: pes1ug22cs578/healthchecker-backend:latest
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    image: pes1ug22cs578/healthchecker-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped